apiVersion: v1
kind: ConfigMap
metadata:
  name: homebite-config
  namespace: homebite
data:
  APP_ENV: "production"
  DEBUG: "false"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-broker:9092"
  KAFKA_TOPIC_ORDER_CREATED: "order.created"
  KAFKA_TOPIC_CHEF_ASSIGNED: "chef.assigned"
  KAFKA_TOPIC_DELIVERY_STARTED: "delivery.started"
  KAFKA_TOPIC_DELIVERY_COMPLETED: "delivery.completed"
  KAFKA_TOPIC_USER_REGISTERED: "user.registered"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  JWT_REFRESH_TOKEN_EXPIRE_DAYS: "7"