apiVersion: v1
kind: ConfigMap
metadata:
  name: homebite-config
  namespace: homebite
data:
  # Database
  DB_HOST: "mysql-service"
  DB_PORT: "3306"

  # Redis
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"

  # Kafka
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  KAFKA_TOPIC_USER_REGISTERED: "user.registered"
  KAFKA_TOPIC_ORDER_CREATED: "order.created"
  KAFKA_TOPIC_CHEF_ASSIGNED: "chef.assigned"
  KAFKA_TOPIC_DELIVERY_STARTED: "delivery.started"
  KAFKA_TOPIC_DELIVERY_COMPLETED: "delivery.completed"

  # App settings
  APP_ENV: "production"
  DEBUG: "false"

  # JWT
  JWT_ALGORITHM: "HS256"
  JWT_ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  JWT_REFRESH_TOKEN_EXPIRE_DAYS: "7"