apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: homebite
  labels:
    app: notification-service
spec:
  replicas: 1   # notification service is stateless and event-driven
                # 1 replica is fine — no user-facing latency impact
  selector:
    matchLabels:
      app: notification-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: tejassh1701/homebite-notification-service:db04f33a86b8b2019a073b9c67d38b7ef5800b6c
          imagePullPolicy: Always
          ports:
            - containerPort: 8005
          envFrom:
            - configMapRef:
                name: homebite-config
          env:
            - name: APP_NAME
              value: "notification_service"
            - name: APP_PORT
              value: "8005"
            - name: KAFKA_CONSUMER_GROUP
              value: "notification-service-group"
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: homebite-secrets
                  key: SMTP_USER
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: homebite-secrets
                  key: SMTP_PASSWORD
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3