# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: homebite
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: homebite
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP

---
# Zookeeper Service
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: homebite
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
  type: ClusterIP

---
# Kafka Service
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  namespace: homebite
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  type: ClusterIP

---
# phpMyAdmin Service — LOCAL ONLY
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: homebite
spec:
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30083
  type: NodePort